# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze Ingestion — ISC DELIVER Domain
# MAGIC
# MAGIC Reads the synthetic SAP-style source files (VBAK/VBAP/LIKP/LIPS/MARA/MARD +
# MAGIC reference tables) and lands them as bronze Delta tables, with an explicit
# MAGIC schema applied and no business transformation.
# MAGIC
# MAGIC **Manual adjustment needed before running (Claude Code has no Databricks
# MAGIC workspace access — these values must be set by you):**
# MAGIC 1. `raw_path` widget — where the CSVs from `data/mock_sap/` were uploaded in
# MAGIC    this workspace (e.g. a Unity Catalog Volume such as
# MAGIC    `/Volumes/main/sap_deliver/raw_files`, or a DBFS path).
# MAGIC 2. `catalog` and `bronze_schema` widgets — the Unity Catalog catalog/schema
# MAGIC    the bronze tables should be created in.

# COMMAND ----------

dbutils.widgets.text("raw_path", "/Volumes/main/sap_deliver/raw_files", "Raw files path")
dbutils.widgets.text("catalog", "main", "Catalog")
dbutils.widgets.text("bronze_schema", "sap_deliver_bronze", "Bronze schema")

raw_path = dbutils.widgets.get("raw_path")
catalog = dbutils.widgets.get("catalog")
bronze_schema = dbutils.widgets.get("bronze_schema")

spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{bronze_schema}")

# COMMAND ----------

from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DateType
from pyspark.sql import functions as F

# COMMAND ----------

# MAGIC %md
# MAGIC ## Source schemas
# MAGIC Explicit schemas (no `inferSchema`) so SAP-style codes (VBELN, MATNR, KUNNR,
# MAGIC etc.) are kept as strings — leading zeros must not be lost — and dates are
# MAGIC typed. This matches the fields generated by
# MAGIC `src/data_generation/generate_synthetic_data.py` and documented in
# MAGIC `docs/data-dictionary.md`.

# COMMAND ----------

SOURCE_TABLES = {
    "VBAK": {
        "file": "VBAK.csv",
        "schema": StructType([
            StructField("VBELN", StringType()),
            StructField("ERDAT", DateType()),
            StructField("AUART", StringType()),
            StructField("KUNNR", StringType()),
            StructField("VKORG", StringType()),
            StructField("VTWEG", StringType()),
            StructField("SPART", StringType()),
        ]),
    },
    "VBAP": {
        "file": "VBAP.csv",
        "schema": StructType([
            StructField("VBELN", StringType()),
            StructField("POSNR", StringType()),
            StructField("MATNR", StringType()),
            StructField("WERKS", StringType()),
            StructField("KWMENG", IntegerType()),
            StructField("MEINS", StringType()),
        ]),
    },
    "LIKP": {
        "file": "LIKP.csv",
        "schema": StructType([
            StructField("VBELN", StringType()),
            StructField("LFART", StringType()),
            StructField("ERDAT", DateType()),
            StructField("LFDAT", DateType()),
            StructField("WADAT_IST", DateType()),
        ]),
    },
    "LIPS": {
        "file": "LIPS.csv",
        "schema": StructType([
            StructField("VBELN", StringType()),
            StructField("POSNR", StringType()),
            StructField("VGBEL", StringType()),
            StructField("VGPOS", StringType()),
            StructField("MATNR", StringType()),
            StructField("WERKS", StringType()),
            StructField("LGORT", StringType()),
            StructField("LFIMG", IntegerType()),
            StructField("MEINS", StringType()),
        ]),
    },
    "MARA": {
        "file": "MARA.csv",
        "schema": StructType([
            StructField("MATNR", StringType()),
            StructField("MAKTX", StringType()),
            StructField("MATKL", StringType()),
            StructField("MEINS", StringType()),
        ]),
    },
    "MARD": {
        "file": "MARD.csv",
        "schema": StructType([
            StructField("MATNR", StringType()),
            StructField("WERKS", StringType()),
            StructField("LGORT", StringType()),
            StructField("LABST", IntegerType()),
        ]),
    },
    "plant_business_unit": {
        "file": "plant_business_unit.csv",
        "schema": StructType([
            StructField("WERKS", StringType()),
            StructField("BUSINESS_UNIT", StringType()),
        ]),
    },
    "delivery_type_decode": {
        "file": "delivery_type_decode.csv",
        "schema": StructType([
            StructField("LFART", StringType()),
            StructField("DESCRIPTION", StringType()),
        ]),
    },
}

# COMMAND ----------

# MAGIC %md
# MAGIC ## Read + write as bronze Delta tables
# MAGIC Adds `_source_file` and `_ingested_at` audit columns only — no business
# MAGIC logic, filtering, or joins happen at this layer.

# COMMAND ----------

for table_name, spec in SOURCE_TABLES.items():
    file_path = f"{raw_path}/{spec['file']}"

    df = (
        spark.read.format("csv")
        .option("header", "true")
        .schema(spec["schema"])
        .load(file_path)
        .withColumn("_source_file", F.lit(spec["file"]))
        .withColumn("_ingested_at", F.current_timestamp())
    )

    target_table = f"{catalog}.{bronze_schema}.bronze_{table_name.lower()}"
    df.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(target_table)

    print(f"{target_table}: {df.count()} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Validation
# MAGIC Quick row counts to sanity-check against the CSVs generated in
# MAGIC `data/mock_sap/` before moving to the silver layer.

# COMMAND ----------

for table_name in SOURCE_TABLES:
    target_table = f"{catalog}.{bronze_schema}.bronze_{table_name.lower()}"
    display(spark.table(target_table).limit(5))
