# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze Ingestion — Auto Loader (`cloudFiles`)
# MAGIC
# MAGIC Alternative to `01_bronze_ingestion.py`'s one-shot batch read: this notebook
# MAGIC ingests the **same source files incrementally**, using Auto Loader
# MAGIC (`cloudFiles`) instead of a plain `spark.read`. Auto Loader tracks which files
# MAGIC it has already processed (via the checkpoint) and only picks up new ones on
# MAGIC each run — the same mechanism used for real streaming ingestion, just run in
# MAGIC batch mode here (`trigger(availableNow=True)`) since there's no live source
# MAGIC system producing files continuously.
# MAGIC
# MAGIC **Verified with two runs, two outcomes:**
# MAGIC 1. First run — `VBAK.csv` (800 orders) + `increment/VBAK_increment.csv` (60
# MAGIC    more, generated by `src/data_generation/generate_incremental_data.py`),
# MAGIC    both already sitting in the volume, get picked up together: 860 rows.
# MAGIC 2. A further `increment2/VBAK_increment2.csv` (10 more orders) was then
# MAGIC    uploaded, and a second run of this notebook brought the table to 870
# MAGIC    rows — confirmed via `groupBy("_source_file")` that only the new file was
# MAGIC    processed on that run, not a full re-read of the other two.
# MAGIC
# MAGIC **Parameters** (widgets, overridable at run time):
# MAGIC 1. `raw_path` — folder Auto Loader watches (both base + `increment/`
# MAGIC    subfolder are read; this table is VBAK only, to keep the demo focused).
# MAGIC 2. `catalog` / `bronze_schema` — target Delta table location.

# COMMAND ----------

dbutils.widgets.text("raw_path", "/Volumes/main/sap_deliver/raw_files", "Raw files path")
dbutils.widgets.text("catalog", "main", "Catalog")
dbutils.widgets.text("bronze_schema", "sap_deliver_bronze", "Bronze schema")

raw_path = dbutils.widgets.get("raw_path")
catalog = dbutils.widgets.get("catalog")
bronze_schema = dbutils.widgets.get("bronze_schema")

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{bronze_schema}")

# COMMAND ----------

from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DateType
from pyspark.sql import functions as F

VBAK_SCHEMA = StructType([
    StructField("VBELN", StringType()),
    StructField("ERDAT", DateType()),
    StructField("AUART", StringType()),
    StructField("KUNNR", StringType()),
    StructField("VKORG", StringType()),
    StructField("VTWEG", StringType()),
    StructField("SPART", StringType()),
])

CHECKPOINT_PATH = f"{raw_path}/_checkpoints/bronze_vbak_autoloader"
SCHEMA_LOCATION = f"{raw_path}/_schemas/bronze_vbak_autoloader"
TARGET_TABLE = f"{catalog}.{bronze_schema}.bronze_vbak_autoloader"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Streaming read (Auto Loader) → streaming write, batch-triggered
# MAGIC `cloudFiles.schemaLocation` lets Auto Loader track schema evolution across
# MAGIC runs (e.g. if a future file adds a column) instead of failing outright.
# MAGIC `trigger(availableNow=True)` processes everything currently available, then
# MAGIC stops — the batch-friendly equivalent of a continuous stream.

# COMMAND ----------

autoloader_df = (
    spark.readStream.format("cloudFiles")
    .option("cloudFiles.format", "csv")
    .option("cloudFiles.schemaLocation", SCHEMA_LOCATION)
    .option("header", "true")
    # raw_path also holds VBAP/LIKP/LIPS/MARA/MARD/reference CSVs — without this
    # filter Auto Loader would try to force every file into the VBAK schema.
    .option("pathGlobFilter", "VBAK*.csv")
    .schema(VBAK_SCHEMA)
    .load(raw_path)
    .withColumn("_source_file", F.col("_metadata.file_path"))
    .withColumn("_ingested_at", F.current_timestamp())
)

query = (
    autoloader_df.writeStream.format("delta")
    .option("checkpointLocation", CHECKPOINT_PATH)
    .trigger(availableNow=True)
    .toTable(TARGET_TABLE)
)
query.awaitTermination()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Validation
# MAGIC Confirmed: 860 rows after the first run (`VBAK.csv` + `increment/`), 870
# MAGIC after `increment2/VBAK_increment2.csv` landed and this notebook re-ran — the
# MAGIC `_source_file` breakdown below shows the checkpoint correctly skipped
# MAGIC re-reading the first two files on the second run.

# COMMAND ----------

display(spark.table(TARGET_TABLE).groupBy("_source_file").count())
print(f"{TARGET_TABLE}: {spark.table(TARGET_TABLE).count()} total rows")
