# Databricks notebook source
# MAGIC %md
# MAGIC # Incremental Upsert (`MERGE INTO`) + Change Data Feed
# MAGIC
# MAGIC `02_silver_transformation.py` / `03_gold_transformation.py` always do a full
# MAGIC `mode("overwrite")` — correct, but wasteful once a table is large: every run
# MAGIC reprocesses everything, even rows that haven't changed. This notebook
# MAGIC demonstrates the incremental alternative:
# MAGIC
# MAGIC 1. Build the same delivery-item shape as `02_silver_transformation.py`, but
# MAGIC    only for `data/mock_sap/increment/*.csv` (the "day 2" batch — new orders
# MAGIC    and deliveries, generated by `src/data_generation/generate_incremental_data.py`).
# MAGIC 2. Inject one manufactured **correction** to an already-existing delivery
# MAGIC    item (a `delivered_quantity` fix) alongside the genuinely new rows, so the
# MAGIC    `MERGE` below has to do both an INSERT and an UPDATE — not just appends.
# MAGIC 3. `MERGE INTO silver_delivery_item` and `MERGE INTO fact_delivery_item`
# MAGIC    (recalculating KPIs for just the touched rows) instead of overwriting
# MAGIC    either table wholesale.
# MAGIC 4. Enable Change Data Feed on `fact_delivery_item` and query
# MAGIC    `table_changes()` to see exactly which rows were inserted vs. updated.
# MAGIC
# MAGIC This MERGE is also what gives `04_delta_time_travel.py` a second table
# MAGIC version worth traveling back from.

# COMMAND ----------

dbutils.widgets.text("raw_path", "/Volumes/main/sap_deliver/raw_files", "Raw files path")
dbutils.widgets.text("catalog", "main", "Catalog")
dbutils.widgets.text("silver_schema", "sap_deliver_silver", "Silver schema")
dbutils.widgets.text("gold_schema", "sap_deliver_gold", "Gold schema")

raw_path = dbutils.widgets.get("raw_path")
catalog = dbutils.widgets.get("catalog")
silver_schema = dbutils.widgets.get("silver_schema")
gold_schema = dbutils.widgets.get("gold_schema")

# COMMAND ----------

from pyspark.sql import functions as F
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DateType

# COMMAND ----------

# MAGIC %md
# MAGIC ## Read the increment batch (same schemas as `01_bronze_ingestion.py`)
# MAGIC Read directly from CSV rather than through a bronze table — in a real
# MAGIC pipeline this would already be `bronze_*` Delta tables incrementally loaded
# MAGIC (e.g. by `05_bronze_autoloader.py`'s pattern extended to all 4 tables); kept
# MAGIC as a direct read here to keep this notebook self-contained.

# COMMAND ----------

INCREMENT_SCHEMAS = {
    "VBAK": StructType([
        StructField("VBELN", StringType()), StructField("ERDAT", DateType()),
        StructField("AUART", StringType()), StructField("KUNNR", StringType()),
        StructField("VKORG", StringType()), StructField("VTWEG", StringType()),
        StructField("SPART", StringType()),
    ]),
    "VBAP": StructType([
        StructField("VBELN", StringType()), StructField("POSNR", StringType()),
        StructField("MATNR", StringType()), StructField("WERKS", StringType()),
        StructField("KWMENG", IntegerType()), StructField("MEINS", StringType()),
    ]),
    "LIKP": StructType([
        StructField("VBELN", StringType()), StructField("LFART", StringType()),
        StructField("ERDAT", DateType()), StructField("LFDAT", DateType()),
        StructField("WADAT_IST", DateType()),
    ]),
    "LIPS": StructType([
        StructField("VBELN", StringType()), StructField("POSNR", StringType()),
        StructField("VGBEL", StringType()), StructField("VGPOS", StringType()),
        StructField("MATNR", StringType()), StructField("WERKS", StringType()),
        StructField("LGORT", StringType()), StructField("LFIMG", IntegerType()),
        StructField("MEINS", StringType()),
    ]),
}

def read_increment(name):
    return (
        spark.read.format("csv")
        .option("header", "true")
        .schema(INCREMENT_SCHEMAS[name])
        .load(f"{raw_path}/increment/{name}_increment.csv")
    )

inc_vbak, inc_vbap, inc_likp, inc_lips = (read_increment(n) for n in ["VBAK", "VBAP", "LIKP", "LIPS"])
print(f"increment rows: VBAK={inc_vbak.count()} VBAP={inc_vbap.count()} LIKP={inc_likp.count()} LIPS={inc_lips.count()}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Build the increment's delivery-item rows
# MAGIC Same join shape as `02_silver_transformation.py`, sourced from the increment
# MAGIC batch instead of bronze. Shared reference tables (MARA, delivery type decode)
# MAGIC are read from silver — they don't change between batches.

# COMMAND ----------

mara = spark.table(f"{catalog}.{silver_schema}.silver_mara")
dtd = spark.table(f"{catalog}.{silver_schema}.silver_delivery_type_decode") if spark.catalog.tableExists(f"{catalog}.{silver_schema}.silver_delivery_type_decode") else spark.table(f"{catalog}.sap_deliver_bronze.bronze_delivery_type_decode")

increment_delivery_item = (
    inc_lips.alias("lips")
    .join(inc_likp.alias("likp"), F.col("lips.VBELN") == F.col("likp.VBELN"), "left")
    .join(
        inc_vbap.alias("vbap"),
        (F.col("lips.VGBEL") == F.col("vbap.VBELN")) & (F.col("lips.VGPOS") == F.col("vbap.POSNR")),
        "left",
    )
    .join(inc_vbak.alias("vbak"), F.col("vbap.VBELN") == F.col("vbak.VBELN"), "left")
    .join(mara.alias("mara"), F.col("lips.MATNR") == F.col("mara.MATNR"), "left")
    .join(dtd.alias("dtd"), F.col("likp.LFART") == F.col("dtd.LFART"), "left")
    .select(
        F.col("likp.VBELN").alias("delivery_id"),
        F.col("lips.POSNR").alias("delivery_item_id"),
        F.col("vbap.VBELN").alias("sales_order_id"),
        F.col("vbap.POSNR").alias("sales_order_item_id"),
        F.col("vbak.KUNNR").alias("customer_id"),
        F.col("lips.MATNR").alias("material_id"),
        F.col("mara.MAKTX").alias("material_description"),
        F.col("lips.WERKS").alias("plant"),
        F.col("lips.LGORT").alias("storage_location"),
        F.col("likp.LFART").alias("delivery_type_code"),
        F.col("dtd.DESCRIPTION").alias("delivery_type_description"),
        F.col("vbak.ERDAT").alias("order_date"),
        F.col("likp.LFDAT").alias("planned_delivery_date"),
        F.col("likp.WADAT_IST").alias("actual_delivery_date"),
        F.lit(False).alias("has_missing_planned_date"),
        F.col("vbap.KWMENG").alias("order_quantity"),
        F.col("lips.LFIMG").alias("delivered_quantity"),
    )
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Inject one correction to an existing row
# MAGIC Picks one already-merged delivery item and adjusts `delivered_quantity` — a
# MAGIC realistic scenario (a warehouse count correction arriving a day later).
# MAGIC Merging this alongside genuinely new rows means the MERGE below can't just
# MAGIC be a blind append; it has to match keys and choose UPDATE vs INSERT.

# COMMAND ----------

existing_sample = (
    spark.table(f"{catalog}.{silver_schema}.silver_delivery_item")
    .orderBy("delivery_id", "delivery_item_id")
    .limit(1)
)
correction = existing_sample.withColumn(
    "delivered_quantity", F.col("delivered_quantity") + F.lit(5)
)

increment_delivery_item = increment_delivery_item.unionByName(correction)
corrected_key = correction.select("delivery_id", "delivery_item_id").first()
print(f"Correcting delivery_id={corrected_key['delivery_id']} delivery_item_id={corrected_key['delivery_item_id']}")
print(f"Total incoming rows for MERGE (new + 1 correction): {increment_delivery_item.count()}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## `MERGE INTO silver_delivery_item`

# COMMAND ----------

increment_delivery_item.createOrReplaceTempView("increment_delivery_item")

spark.sql(f"""
MERGE INTO {catalog}.{silver_schema}.silver_delivery_item AS target
USING increment_delivery_item AS source
ON target.delivery_id = source.delivery_id AND target.delivery_item_id = source.delivery_item_id
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *
""")

print(f"silver_delivery_item now: {spark.table(f'{catalog}.{silver_schema}.silver_delivery_item').count()} rows")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Recalculate gold rows for just the touched keys, then `MERGE INTO fact_delivery_item`
# MAGIC Same KPI logic as `03_gold_transformation.py`, applied only to the rows that
# MAGIC changed — not the whole table.

# COMMAND ----------

TOLERANCE_HOURS = 24
plant_bu = spark.table(f"{catalog}.{silver_schema}.silver_plant_business_unit")

increment_fact = (
    increment_delivery_item.join(plant_bu, on="plant", how="left")
    .withColumn("lead_time_days", F.datediff("actual_delivery_date", "order_date"))
    .withColumn(
        "is_on_time",
        F.when(F.col("has_missing_planned_date"), F.lit(None).cast("boolean")).otherwise(
            F.col("actual_delivery_date") <= F.expr(f"planned_delivery_date + INTERVAL {TOLERANCE_HOURS} HOURS")
        ),
    )
    .withColumn("is_in_full", F.col("delivered_quantity") >= F.col("order_quantity"))
    .withColumn("is_otif", F.col("is_on_time") & F.col("is_in_full"))
    .select(
        "delivery_id", "delivery_item_id", "sales_order_id", "sales_order_item_id",
        "customer_id", "material_id", "material_description", "plant", "storage_location",
        "delivery_type_code", "delivery_type_description", "order_date",
        "planned_delivery_date", "actual_delivery_date", "order_quantity",
        "delivered_quantity", "lead_time_days", "is_on_time", "is_in_full", "is_otif",
        "business_unit",
    )
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Enable Change Data Feed, then MERGE
# MAGIC CDF has to be enabled *before* the write whose changes you want to capture.

# COMMAND ----------

fact_table = f"{catalog}.{gold_schema}.fact_delivery_item"
spark.sql(f"ALTER TABLE {fact_table} SET TBLPROPERTIES (delta.enableChangeDataFeed = true)")

version_before = spark.sql(f"DESCRIBE HISTORY {fact_table} LIMIT 1").collect()[0]["version"]

increment_fact.createOrReplaceTempView("increment_fact")
spark.sql(f"""
MERGE INTO {fact_table} AS target
USING increment_fact AS source
ON target.delivery_id = source.delivery_id AND target.delivery_item_id = source.delivery_item_id
WHEN MATCHED THEN UPDATE SET *
WHEN NOT MATCHED THEN INSERT *
""")

version_after = spark.sql(f"DESCRIBE HISTORY {fact_table} LIMIT 1").collect()[0]["version"]
print(f"{fact_table}: version {version_before} -> {version_after}, {spark.table(fact_table).count()} rows total")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Validate via `table_changes()`
# MAGIC Should show `insert` for the new delivery items and `update_preimage` /
# MAGIC `update_postimage` for the one corrected row — proof the MERGE did a real
# MAGIC upsert, not just an append.

# COMMAND ----------

changes = spark.sql(f"""
SELECT _change_type, COUNT(*) AS row_count
FROM table_changes('{fact_table}', {version_before}, {version_after})
GROUP BY _change_type
ORDER BY _change_type
""")
display(changes)
