"""
Generates a small "day 2" incremental batch of new orders/deliveries, reusing
the existing customers/materials/plants from data/mock_sap/ so foreign keys
still resolve against the already-ingested bronze/silver/gold tables.

Output: CSV files under data/mock_sap/increment/ — used to demonstrate Auto
Loader (incremental file arrival), MERGE INTO (upsert), and Change Data Feed
(notebooks/05_bronze_autoloader.py, notebooks/06_merge_and_cdf.py).

Continues numbering after the existing max VBELN/delivery number so nothing
collides with the original batch generated by generate_synthetic_data.py.
"""
import csv
import random
from datetime import date

from generate_synthetic_data import (
    ALL_PLANTS,
    DELIVERY_TYPES,
    DELIVERY_TYPE_WEIGHTS,
    DISTR_CHANNEL,
    DIVISION,
    ORDER_TYPES,
    ORDER_TYPE_WEIGHTS,
    OUTPUT_DIR,
    SALES_ORG,
    STORAGE_LOCATIONS,
    UNIT,
    write_csv,
)

INCREMENT_DIR = OUTPUT_DIR / "increment"
SEED = 43  # distinct from the base batch's seed (42)
NUM_ORDERS = 60
ORDER_DATE_RANGE = (date(2025, 7, 1), date(2025, 7, 15))
LEAD_TIME_DAYS_RANGE = (3, 10)
PCT_LATE_DELIVERY = 0.25
LATE_RANGE = (1, 7)
ON_TIME_RANGE = (-2, 0)
PCT_SHORT_SHIPMENT = 0.15
SHORT_RANGE = (0.5, 0.95)


def load_existing_ids():
    with open(OUTPUT_DIR / "VBAK.csv") as f:
        vbak_rows = list(csv.DictReader(f))
    with open(OUTPUT_DIR / "MARA.csv") as f:
        mara_rows = list(csv.DictReader(f))

    customers = sorted({r["KUNNR"] for r in vbak_rows})
    max_vbeln = max(int(r["VBELN"]) for r in vbak_rows)

    with open(OUTPUT_DIR / "LIKP.csv") as f:
        likp_rows = list(csv.DictReader(f))
    max_delivery = max(int(r["VBELN"]) for r in likp_rows)

    return customers, mara_rows, max_vbeln, max_delivery


def generate_vbak_increment(num_orders, customers, next_vbeln, start_date, end_date):
    from generate_synthetic_data import random_date_between

    rows = []
    for i in range(num_orders):
        order_type = random.choices(list(ORDER_TYPES), weights=ORDER_TYPE_WEIGHTS)[0]
        rows.append({
            "VBELN": str(next_vbeln + i),
            "ERDAT": random_date_between(start_date, end_date).isoformat(),
            "AUART": order_type,
            "KUNNR": random.choice(customers),
            "VKORG": SALES_ORG,
            "VTWEG": DISTR_CHANNEL,
            "SPART": DIVISION,
        })
    return rows


def generate_vbap_increment(vbak_rows, mara_rows):
    rows = []
    for order in vbak_rows:
        for pos in range(1, random.randint(1, 3) + 1):
            mat = random.choice(mara_rows)
            rows.append({
                "VBELN": order["VBELN"],
                "POSNR": f"{pos * 10:06d}",
                "MATNR": mat["MATNR"],
                "WERKS": random.choice(ALL_PLANTS),
                "KWMENG": random.randint(1, 100),
                "MEINS": UNIT,
            })
    return rows


def generate_likp_lips_increment(vbak_rows, vbap_rows, next_delivery):
    from datetime import timedelta

    items_by_order = {}
    for item in vbap_rows:
        items_by_order.setdefault(item["VBELN"], []).append(item)

    likp_rows, lips_rows = [], []
    delivery_counter = next_delivery

    for order in vbak_rows:
        items = items_by_order.get(order["VBELN"], [])
        if not items:
            continue

        delivery_id = str(delivery_counter)
        delivery_counter += 1

        order_date = date.fromisoformat(order["ERDAT"])
        planned_date = order_date + timedelta(days=random.randint(*LEAD_TIME_DAYS_RANGE))
        if random.random() < PCT_LATE_DELIVERY:
            delta_days = random.randint(*LATE_RANGE)
        else:
            delta_days = random.randint(*ON_TIME_RANGE)
        actual_date = planned_date + timedelta(days=delta_days)

        delivery_type = random.choices(list(DELIVERY_TYPES), weights=DELIVERY_TYPE_WEIGHTS)[0]

        likp_rows.append({
            "VBELN": delivery_id,
            "LFART": delivery_type,
            "ERDAT": order_date.isoformat(),
            "LFDAT": planned_date.isoformat(),
            "WADAT_IST": actual_date.isoformat(),
        })

        for pos, item in enumerate(items, start=1):
            if random.random() < PCT_SHORT_SHIPMENT:
                delivered_qty = max(1, round(item["KWMENG"] * random.uniform(*SHORT_RANGE)))
            else:
                delivered_qty = item["KWMENG"]

            lips_rows.append({
                "VBELN": delivery_id,
                "POSNR": f"{pos * 10:06d}",
                "VGBEL": item["VBELN"],
                "VGPOS": item["POSNR"],
                "MATNR": item["MATNR"],
                "WERKS": item["WERKS"],
                "LGORT": random.choice(STORAGE_LOCATIONS),
                "LFIMG": delivered_qty,
                "MEINS": UNIT,
            })

    return likp_rows, lips_rows


def main():
    random.seed(SEED)
    customers, mara_rows, max_vbeln, max_delivery = load_existing_ids()

    vbak_rows = generate_vbak_increment(
        NUM_ORDERS, customers, max_vbeln + 1, *ORDER_DATE_RANGE
    )
    vbap_rows = generate_vbap_increment(vbak_rows, mara_rows)
    likp_rows, lips_rows = generate_likp_lips_increment(vbak_rows, vbap_rows, max_delivery + 1)

    INCREMENT_DIR.mkdir(parents=True, exist_ok=True)
    write_csv_to = lambda rows, name: write_csv(rows, f"increment/{name}")
    write_csv_to(vbak_rows, "VBAK_increment.csv")
    write_csv_to(vbap_rows, "VBAP_increment.csv")
    write_csv_to(likp_rows, "LIKP_increment.csv")
    write_csv_to(lips_rows, "LIPS_increment.csv")


if __name__ == "__main__":
    main()
